In [4]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import gmaps
from pprint import pprint

In [5]:
# Import API key
from api_keys import gkey

In [6]:
df = pd.read_csv('cities.csv', index_col=0)
df

,Country,lat,long,city_temps,perc_humidity,perc_cloudiness,wind_speed
City,,,,,,,
London,GB,51.51,-0.13,41.81,81,75,11.41
Milan,IT,45.46,9.19,42.80,48,0,1.12
Rikitea,PF,-23.12,-134.97,79.11,78,100,17.52
Kutum,SD,14.20,24.67,49.10,18,0,7.67
Hofn,IS,64.25,-15.21,28.15,82,100,23.33
...,...,...,...,...,...,...,...
Synya,RU,65.37,58.04,23.43,90,100,12.71
Bilibino,RU,68.05,166.44,-17.32,96,0,3.31
Sal Rei,CV,16.18,-22.92,69.80,83,20,11.41
Esim,GH,4.87,-2.24,79.75,81,9,4.88
Burgersdorp,ZA,-31.00,26.33,63.72,55,33,2.93

In [7]:
#configure gmap
gmaps.configure(api_key = gkey)

In [8]:
#drop any NaN
df = df.dropna()
df

,Country,lat,long,city_temps,perc_humidity,perc_cloudiness,wind_speed
City,,,,,,,
London,GB,51.51,-0.13,41.81,81,75,11.41
Milan,IT,45.46,9.19,42.80,48,0,1.12
Rikitea,PF,-23.12,-134.97,79.11,78,100,17.52
Kutum,SD,14.20,24.67,49.10,18,0,7.67
Hofn,IS,64.25,-15.21,28.15,82,100,23.33
...,...,...,...,...,...,...,...
Synya,RU,65.37,58.04,23.43,90,100,12.71
Bilibino,RU,68.05,166.44,-17.32,96,0,3.31
Sal Rei,CV,16.18,-22.92,69.80,83,20,11.41
Esim,GH,4.87,-2.24,79.75,81,9,4.88
Burgersdorp,ZA,-31.00,26.33,63.72,55,33,2.93

In [9]:
# Store 'Lat' and 'Lng' into  locations 
locations = df[["lat", "long"]].astype(float)

In [10]:
#isolate % humidity and convert it to a float type
city_humidity = df["perc_humidity"].astype(float)

In [11]:
# Create a poverty Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=city_humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
#create ideal conditions for a vacation
vac_df = df[df['city_temps']>70]
vac_df=vac_df[vac_df['perc_humidity']<60]
vac_df=vac_df[vac_df['perc_cloudiness']<30]
vac_df=vac_df[vac_df['wind_speed']<20]
vac_df=vac_df.reset_index()
vac_df['Hotel']=''
vac_df

,City,Country,lat,long,city_temps,perc_humidity,perc_cloudiness,wind_speed,Hotel
0,Hilo,US,19.73,-155.09,76.73,57,20,9.17,
1,Alice Springs,AU,-23.70,133.88,75.20,36,0,3.36,
2,Ondjiva,AO,-17.07,15.73,77.97,29,0,4.85,
3,Araouane,ML,18.90,-3.53,76.12,15,0,9.62,
4,Innisfail,AU,-17.53,146.03,73.56,58,0,5.03,
5,Nioro,GM,13.35,-15.75,85.44,12,0,8.52,
6,Cabo San Lucas,MX,22.89,-109.91,70.11,52,5,4.70,
7,Santa Maria,BR,-29.68,-53.81,84.20,51,20,14.99,
8,Solapur,IN,17.68,75.92,71.47,55,0,7.07,
9,Dakar,SN,14.69,-17.44,77.07,57,0,13.87,
10,Praia,CV,14.92,-23.51,77.00,22,0,17.22,
11,Jimani,DO,18.49,-71.85,89.60,46,0,19.46,
12,Yulara,AU,-25.24,130.99,84.20,26,0,8.05,
13,Baragua,CU,21.70,-78.63,89.38,39,0,12.08,
14,Contamana,PE,-7.33,-75.02,95.54,33,4,6.11,
15,Gbadolite,CD,4.28,21.02,72.27,33,0,1.16,
16,Calvinia,ZA,-31.47,19.78,76.33,34,0,6.13,
17,Mangulile,HN,15.07,-86.80,77.74,38,0,6.85,
18,Lethem,GY,3.38,-59.80,94.57,35,22,12.41,
19,Adrar,MR,20.50,-10.07,76.39,28,0,8.55,
20,Monte Santo,BR,-10.44,-39.33,80.55,53,19,4.99,
21,Durazno,UY,-33.41,-56.50,82.00,39,13,13.35,
22,Atar,MR,20.52,-13.05,77.02,21,0,11.45,
23,Presidencia Roque Saenz Pena,AR,-26.79,-60.44,95.18,24,0,4.83,
24,Sedhiou,SN,12.71,-15.56,82.40,45,0,6.89,
25,Ciudad Lazaro Cardenas,MX,17.96,-102.20,85.19,45,0,8.97,
26,Nacozari,MX,25.34,-108.26,72.81,39,0,8.01,
27,Halol,IN,22.50,73.47,70.48,29,0,4.59,
28,Necochea,AR,-38.55,-58.74,79.68,50,0,13.00,
29,Gunjur,GM,13.20,-16.73,82.40,51,5,9.17,
30,Reconquista,AR,-29.15,-59.65,96.48,19,0,7.92,
31,Nueve de Julio,AR,-35.44,-60.88,85.69,38,0,1.99,

In [13]:
vac_locations = vac_df[["lat", "long"]].astype(float)
vac_locations
#use iterrows to iterate through pandas dataframe
for index, row in vac_locations.iterrows():

    # get restaurant type from df
    city_coords = row['lat'],  row['long']
    print(city_coords)

(19.73, -155.09)
(-23.7, 133.88)
(-17.07, 15.73)
(18.9, -3.53)
(-17.53, 146.03)
(13.35, -15.75)
(22.89, -109.91)
(-29.68, -53.81)
(17.68, 75.92)
(14.69, -17.44)
(14.92, -23.51)
(18.49, -71.85)
(-25.24, 130.99)
(21.7, -78.63)
(-7.33, -75.02)
(4.28, 21.02)
(-31.47, 19.78)
(15.07, -86.8)
(3.38, -59.8)
(20.5, -10.07)
(-10.44, -39.33)
(-33.41, -56.5)
(20.52, -13.05)
(-26.79, -60.44)
(12.71, -15.56)
(17.96, -102.2)
(25.34, -108.26)
(22.5, 73.47)
(-38.55, -58.74)
(13.2, -16.73)
(-29.15, -59.65)
(-35.44, -60.88)

In [14]:

# # geocoordinates
# for city in vac_locations:
#     target_coordinates = city
#     target_search ='hotel'
#     target_radius = 5000
#     target_type = "lodging"

# # set up a parameters dictionary
# params = {
#     "location": target_coordinates,
#     "keyword": target_search,
#     "radius": target_radius,
#     "type": target_type,
#     "key": gkey
# }

# # base url
# base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# # run a request using our params dictionary
# response = requests.get(base_url, params=params).json()

# print(response)

In [15]:

#geocoordinates

target_search ='hotel'
target_radius = 5000
target_type = "lodging"

# set up a parameters dictionary
params = {
    
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": gkey
}


# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

#use iterrows to iterate through pandas dataframe
for index, row in vac_df.iterrows():

    # get restaurant type from df
    lat = row['lat']  
    long = row['long']
    city_coords = f'{lat},{long}'

    # add keyword to params dict
    params['location'] = city_coords

    # # run a request using our params dictionary
    response = requests.get(base_url, params=params)

    # #convert response to a json 
    hotel_locations = response.json()
   # pprint(hotel_locations)
    try:
        results = hotel_locations['results']
        hotel = results[0]['name']
        vac_df.loc[index, 'Hotel']=hotel
    except:
        print("no hotels here")

no hotels here
no hotels here
no hotels here
no hotels here
no hotels here
no hotels here
no hotels here

In [16]:
vac_df

,City,Country,lat,long,city_temps,perc_humidity,perc_cloudiness,wind_speed,Hotel
0,Hilo,US,19.73,-155.09,76.73,57,20,9.17,Grand Naniloa Hotel Hilo - a DoubleTree by Hilton
1,Alice Springs,AU,-23.70,133.88,75.20,36,0,3.36,DoubleTree by Hilton Hotel Alice Springs
2,Ondjiva,AO,-17.07,15.73,77.97,29,0,4.85,
3,Araouane,ML,18.90,-3.53,76.12,15,0,9.62,
4,Innisfail,AU,-17.53,146.03,73.56,58,0,5.03,Commonwealth Hotel
5,Nioro,GM,13.35,-15.75,85.44,12,0,8.52,
6,Cabo San Lucas,MX,22.89,-109.91,70.11,52,5,4.70,Waldorf Astoria Los Cabos Pedregal
7,Santa Maria,BR,-29.68,-53.81,84.20,51,20,14.99,Park Hotel Morotin
8,Solapur,IN,17.68,75.92,71.47,55,0,7.07,Balaji Sarovar Premiere
9,Dakar,SN,14.69,-17.44,77.07,57,0,13.87,"Radisson Blu Hotel, Dakar Sea Plaza"
10,Praia,CV,14.92,-23.51,77.00,22,0,17.22,Hotel VIP Praia
11,Jimani,DO,18.49,-71.85,89.60,46,0,19.46,Hotel Jimani
12,Yulara,AU,-25.24,130.99,84.20,26,0,8.05,Sails in the Desert
13,Baragua,CU,21.70,-78.63,89.38,39,0,12.08,Hotel Itabo
14,Contamana,PE,-7.33,-75.02,95.54,33,4,6.11,Hotel ZavalaÂ´S
15,Gbadolite,CD,4.28,21.02,72.27,33,0,1.16,
16,Calvinia,ZA,-31.47,19.78,76.33,34,0,6.13,Carmel Villa B&B or Self-Catering
17,Mangulile,HN,15.07,-86.80,77.74,38,0,6.85,
18,Lethem,GY,3.38,-59.80,94.57,35,22,12.41,Takutu Hotel
19,Adrar,MR,20.50,-10.07,76.39,28,0,8.55,
20,Monte Santo,BR,-10.44,-39.33,80.55,53,19,4.99,Hotel Santo AndrÃ©
21,Durazno,UY,-33.41,-56.50,82.00,39,13,13.35,Hotel Durazno
22,Atar,MR,20.52,-13.05,77.02,21,0,11.45,Odar kanawal
23,Presidencia Roque Saenz Pena,AR,-26.79,-60.44,95.18,24,0,4.83,Apart temporario LHOTAK
24,Sedhiou,SN,12.71,-15.56,82.40,45,0,6.89,HÃ´tel Palmeraie
25,Ciudad Lazaro Cardenas,MX,17.96,-102.20,85.19,45,0,8.97,Hotel Zirahuen
26,Nacozari,MX,25.34,-108.26,72.81,39,0,8.01,
27,Halol,IN,22.50,73.47,70.48,29,0,4.59,Hotel Nilkanth Inn
28,Necochea,AR,-38.55,-58.74,79.68,50,0,13.00,Hotel Real
29,Gunjur,GM,13.20,-16.73,82.40,51,5,9.17,"Footsteps Eco Lodge, The Gambia"
30,Reconquista,AR,-29.15,-59.65,96.48,19,0,7.92,Hotel Ychoalay Caz
31,Nueve de Julio,AR,-35.44,-60.88,85.69,38,0,1.99,Grand Hotel Libertad - Restaurante Duomo

In [17]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in vac_df.iterrows()]
locations = vac_df[["lat", "long"]]

In [18]:
# Add marker layer ontop of heat map
var marker = new google.maps.Marker({position: uluru, map: map})
hotel_marks = gmaps.heatmap_layer(locations)

fig.add_layer(hotel_marks)

fig

# Display Map

SyntaxError: invalid syntax (<ipython-input-18-1a673f61f918>, line 2)