In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import json
from pprint import pprint

# Import API key
from api_keys import weather_api_key

In [4]:
df = pd.read_csv('cities.csv', index_col=0)
df

                  lat  city_temps  perc_humidity  perc_cloudiness  wind_speed
City
0                 NaN         NaN            NaN              NaN         NaN
Cabo San Lucas  22.89       70.50           68.0             40.0        6.93
Rikitea        -23.12       79.34           78.0              0.0       11.39
Puerto Ayora    -0.74       78.30           69.0             75.0        8.05
Noumea         -22.28       89.04           44.0             20.0       12.75
...               ...         ...            ...              ...         ...
Ixtapa          20.70       77.92           65.0             40.0        9.17
Matale           7.47       62.15           96.0            100.0        3.22
Adre            13.47       57.83           16.0              0.0       15.37
Sistranda       63.73       38.10           93.0             75.0       14.99
Statesboro      32.45       52.59           61.0             90.0        5.32

[614 rows x 5 columns]