In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import gmaps
from pprint import pprint

# Import API key
from api_keys import gkey
gkey

'AIzaSyAIZnufTPwYIJDg11Hra6ZsQX0vOlTZRO4'

In [81]:
df = pd.read_csv('cities.csv', index_col=0)
df

,lat,long,city_temps,perc_humidity,perc_cloudiness,wind_speed
City,,,,,,
Mahebourg,-20.41,57.70,75.09,78.0,40.0,8.05
Iqaluit,63.75,-68.51,-25.29,67.0,40.0,9.17
Cabedelo,-6.98,-34.83,82.40,83.0,20.0,6.93
0,NaN,NaN,NaN,NaN,NaN,NaN
Rikitea,-23.12,-134.97,79.34,78.0,0.0,11.39
...,...,...,...,...,...,...
Northam,51.03,-4.22,45.25,91.0,43.0,13.00
Maragogi,-9.01,-35.22,81.82,81.0,79.0,14.58
0,NaN,NaN,NaN,NaN,NaN,NaN
Auki,-8.77,160.70,84.65,73.0,99.0,8.66
OEstersund,63.18,14.64,28.60,100.0,100.0,19.46

In [82]:
#configure gmap
gmaps.configure(api_key = gkey)

In [83]:
#drop any NaN
df = df.dropna()
df

,lat,long,city_temps,perc_humidity,perc_cloudiness,wind_speed
City,,,,,,
Mahebourg,-20.41,57.70,75.09,78.0,40.0,8.05
Iqaluit,63.75,-68.51,-25.29,67.0,40.0,9.17
Cabedelo,-6.98,-34.83,82.40,83.0,20.0,6.93
Rikitea,-23.12,-134.97,79.34,78.0,0.0,11.39
Chepen,-7.22,-79.45,66.20,29.0,75.0,11.41
...,...,...,...,...,...,...
Galesong,-5.32,119.37,84.20,74.0,20.0,4.70
Northam,51.03,-4.22,45.25,91.0,43.0,13.00
Maragogi,-9.01,-35.22,81.82,81.0,79.0,14.58
Auki,-8.77,160.70,84.65,73.0,99.0,8.66
OEstersund,63.18,14.64,28.60,100.0,100.0,19.46

In [84]:
# Store 'Lat' and 'Lng' into  locations 
locations = df[["lat", "long"]].astype(float)

In [85]:
#isolate % humidity and convert it to a float type
city_humidity = df["perc_humidity"].astype(float)

In [86]:
# Create a poverty Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=city_humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [87]:
#create ideal conditions for a vacation
vac_df = df[df['city_temps']>70]
vac_df=vac_df[vac_df['perc_humidity']<60]
vac_df=vac_df[vac_df['perc_cloudiness']<30]
vac_df=vac_df[vac_df['wind_speed']<20]
vac_df=vac_df.reset_index()

In [88]:
cities = vac_df["City"]
cities

0              Kwinana
1            Busselton
2       Xochistlahuaca
3                 Buin
4           San Rafael
5            Taoudenni
6     San Buenaventura
7        Alice Springs
8             Mokobeng
9            El Fuerte
10             Kahului
11           Matamoros
12                 Ewo
13               Dubbo
14             Anahuac
15                Yaan
16              Yulara
17               Praia
Name: City, dtype: object

In [89]:

# geocoordinates
for city in cities:
    target_city = "city"
    target_search ='hotel'
    target_radius = 5000
    target_type = "lodging"

# set up a parameters dictionary
params = {
    "location": target_city,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": gkey
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params).json()